version: 2.1

commands:
  update_chrome_command:
    steps:
      - browser-tools/install-browser-tools:
          replace-existing-chrome: true
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install AND update Chrome
  test_command:
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing npm dependency
          command: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build_command:
    parameters:
      environment:
        type: string
        default: dev
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Create Production Build
          command: npm run build -- --prod --configuration=<< parameters.environment >> --no-progress

jobs:
  unit_test:
    working_directory: ~/test-results
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - test_command
      - run:
          name: Ejecutando test de unidad
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - store_test_results:
          path: ~/test-results/report
  integration_test:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - update_chrome_command
      - test_command
      - run:
          name: Ejecutando test de unidad
          command: |
            google-chrome --version
            chromedriver --version
            npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - store_test_results:
          path: ~/report
  build:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - build_command
  publish:
    docker:
      - image: circleci/node:10.16.3-browsers
    parameters:
      azure_repo_url:
        type: string
      environment:
        type: string
        default: "dev"
    steps:
      - build_command:
          environment: << parameters.environment >>
      - run:
          name: Deploy Develop to Azure
          command: |
            USER_EMAIL=$(git log -n 1 --format=%ae $CIRCLE_SHA1)
            USER_NAME=$(git log -n 1 --format=%cN $CIRCLE_SHA1)
            cd dist
            git init
            git config push.default simple
            git config user.email "$USER_EMAIL"
            git config user.name "$USER_NAME"
            git remote add azure "<< parameters.azure_repo_url >>"
            git fetch azure
            if [ `git branch --list -r azure/master` ]; then
              git reset azure/master
            fi
            git add --all
            git commit -m "Build $CIRCLE_BUILD_NUM" -m "Commit $CIRCLE_SHA1"
            git push azure master

orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - unit_test
      # - integration_test
      - build:
          requires:
            #- unit_test
            # - integration_test
      - publish:
          environment: "dev"
          azure_repo_url: $AZURE_REPOSITORY_DEV_URL
          filters:
            branches:
              only: dev
          requires:
            #- unit_test
            # - integration_test
            - build
      - publish:
          environment: "test"
          azure_repo_url: $AZURE_REPOSITORY_TEST_URL
          filters:
            branches:
              only: test
          requires:
            #- unit_test
            # - integration_test
            - build
